# Generated by Django 5.1.7 on 2025-03-13 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beauty_Types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Beauty_products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.ImageField(null=True, upload_to='')),
                ('product_name', models.CharField(max_length=100)),
                ('product_price', models.IntegerField(null=0)),
                ('Beauty_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beauty_app.beauty_types')),
            ],
        ),
    ]
