# Generated by Django 5.1.7 on 2025-03-14 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beauty_products',
            old_name='Beauty_Name',
            new_name='Beauty_caterogy_type',
        ),
    ]
