# Generated by Django 5.1.7 on 2025-03-14 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_app', '0002_rename_beauty_name_beauty_products_beauty_caterogy_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='beauty_products',
            name='product_caterogy',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='beauty_products',
            name='Beauty_caterogy_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='beauty_app.beauty_types'),
        ),
    ]
