# Generated by Django 5.1.7 on 2025-03-15 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_app', '0003_beauty_products_product_caterogy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginSignup_process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('user_email', models.EmailField(max_length=50)),
                ('user_password', models.CharField(max_length=100)),
            ],
        ),
    ]
